name: verif code
on: [push]
jobs:
  example:
    name: Demo-Cours
    runs-on: ubuntu-latest
    steps:
      - name: faire checkout
        uses: actions/checkout@v4
      - name: liste fichier
        run: ls -la

      - name: PHP CS
        run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
      
      - uses: thenabeel/action-phpcs@v8
        with:
          files: "**.php"
          phpcs_path: php phpcs.phar
          standard: phpcs.xml

        

      - name: working dir
        run: pwd