name: verif code
on: [push]
jobs:
  example:
    name: Demo-Cours
    runs-on: ubuntu-latest
    steps:
      - name: faire checkout
        uses: actions/checkout@v4
      - name: liste fichier
        run: ls -la

      - name: PHP CS
        run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
      
      #- name: Verifier le code
      ##  run: |
       #   php phpcs.phar --standard=PSR1 --extensions=php --ignore=vendor/ .

      - name: Verification architecture
        run: bash src/script.sh

      - name: working dir
        run: pwd

  example1:
    name: Installer et tester
    runs-on: ubuntu-latest
    steps:
      - name: faire checkout
        uses: actions/checkout@v4

      - name: PHP UNIT
        run: wget -O phpunit https://phar.phpunit.de/phpunit-12.phar
      
      - name: Droit
        run: chmod +x phpunit
      
      - name: Test
        run: php phpunit tests/MesDatesTest.php

  exemple2:
    name: TEST CAFEE
    runs-on: ubuntu-latest
    steps:
      - name: faire checkout
        uses: actions/checkout@v4

      - name: Utilisation de php
        uses: shivammathur/setup-php@v2

      - name: Démarrer le serveur
        run: php -S localhost:8080 -t public &
      
      - name: Attendre le serveur
        run: sleep 5
        
      - name: Verfication du formulaire
        run: http://localhost:8000/site/formulaire.php
